[package]
name = "ghr"
description = "Yet another repository management with auto-attaching profiles."
version = "0.3.8"
license = "MIT"
homepage = "https://github.com/siketyan/ghr"
repository = "https://github.com/siketyan/ghr.git"
readme = "README.md"
rust-version = "1.69.0"
edition = "2021"
authors = [
    "Naoki Ikeguchi <me@s6n.jp>",
]

[dependencies]
anyhow = "1.0"
async-hofs = "0.1.1"
async-trait = "0.1.68"
build-info = "0.0.31"
clap = { version = "4.3", features = ["derive"] }
console = "0.15.2"
dialoguer = "0.10.4"
dirs = "5.0"
git2 = "0.17.1"
itertools = "0.10.5"
indicatif = "0.17.1"
lazy_static = "1.4"
regex = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_regex = "1.1"
serde_with = "3.0"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.14"
toml = "0.7.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = "2.3"
walkdir = "2.3"

gh-config = { version = "0.2.1", optional = true }
octocrab = { version = "0.21.0", optional = true }

[target.'cfg(windows)'.dependencies.windows]
version = "0.48.0"
features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]

[build-dependencies]
build-info-build = "0.0.31"

[features]
default = ["github"]
vendored = ["git2/vendored-libgit2", "git2/vendored-openssl"]
github = ["gh-config", "octocrab"]
