[package]
name = "ghr"
description = "Yet another repository management with auto-attaching profiles."
version = "0.4.2"
license = "MIT"
homepage = "https://github.com/siketyan/ghr"
repository = "https://github.com/siketyan/ghr.git"
readme = "README.md"
rust-version = "1.74.0"
edition = "2021"
authors = [
    "Naoki Ikeguchi <me@s6n.jp>",
]

[dependencies]
anyhow = "1.0"
async-hofs = "0.1.1"
async-trait = "0.1.77"
build-info = "0.0.36"
clap = { version = "4.5", features = ["derive"] }
console = "0.15.8"
dialoguer = "0.11.0"
dirs = "5.0"
git2 = "0.18.2"
itertools = "0.12.1"
indicatif = "0.17.8"
lazy_static = "1.4"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_regex = "1.1"
serde_with = "3.7"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.14"
toml = "0.8.11"
tracing = "0.1.39"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5"
walkdir = "2.5"

gh-config = { version = "0.3.2", optional = true }
octocrab = { version = "0.36.0", optional = true }

[target.'cfg(windows)'.dependencies.windows]
version = "0.54.0"
features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]

[build-dependencies]
build-info-build = "0.0.36"

[features]
default = ["github"]
vendored = ["git2/vendored-libgit2", "git2/vendored-openssl"]
github = ["gh-config", "octocrab"]
